const dataOder = [
    {
        id: '5',
        imagecolor: 'ic_main_suadonhang_erro',
        textid: '355895476',
        textstore: 'Gia Huy Mobile',
        imageerro: 'ic_main_suadonhang_erro',
        textstatus: 'Sửa đơn hàng',
        texttimedate: '16:40 - Quá 2 ngày',
        texterro: '16:40 - Khách hàng không có nhà',
        textname: 'Nguyễn Văn A',
        textaddress:
            'Số 10 phố Quần Ngựa, P Liễu Giai, Văn Cao, Ba Đình, Hà Nội',
        imagecall: 'ic_main_telephone',
        textcall: 'Gọi điện',
        imagesms: 'ic_main_sms',
        textsms: 'Nhắn tin',
        imagestatus: 'ic_main_noidung',
        textnoidung: 'Thành công',
        imagechuyen: 'ic_main_chuyentt',
        textchuyen: 'Chuyển TT'
    },
    {
        id: '1',
        imagecolor: 'ic_main_suadonhang_erro',
        textid: '355895476',
        textstore: 'Gia Huy Mobile',
        imageerro: 'ic_main_suadonhang_erro',
        textstatus: 'Sửa đơn hàng',
        texttimedate: '16:40 - Quá 2 ngày',
        texterro: '16:40 - Khách hàng không có nhà',
        textname: 'Nguyễn Diệu Nga',
        textaddress:
            'Số 10 phố Quần Ngựa, P Liễu Giai, Văn Cao, Ba Đình, Hà Nội',
        imagecall: 'ic_main_telephone',
        textcall: 'Gọi điện',
        imagesms: 'ic_main_sms',
        textsms: 'Nhắn tin',
        imagestatus: 'ic_main_noidung',
        textnoidung: 'Thành công',
        imagechuyen: 'ic_main_chuyentt',
        textchuyen: 'Chuyển TT'
    },
    {
        id: '2',
        textid: '372145951',
        imagecolor: 'ic_main_ttdonhang_orange',
        textstore: 'Thái Mobile',
        imageerro: 'ic_main_giao1phan_erro',
        textstatus: '  Giao 1 phần',
        texttimedate: '16:40 - Quá 2 ngày',
        texterro: '16:40 - Khách hàng không có nhà',
        textname: 'Nguyễn Vân Anh',
        textaddress: 'Số 10 đường Cổ Nhuế, quận Bắc Từ Liêm, Hà Nội',
        imagecall: 'ic_main_telephone',
        textcall: 'Gọi điện',
        imagesms: 'ic_main_sms',
        textsms: 'Nhắn tin',
        imagestatus: 'ic_main_noidung',
        textnoidung: 'Thành công',
        imagechuyen: 'ic_main_chuyentt',
        textchuyen: 'Chuyển TT'
    },
    {
        id: '3',
        textid: '12345678',
        imagecolor: 'ic_main_suadonhang_erro',
        textstore: 'Huy Mobile',
        imageerro: 'ic_main_suadonhang_erro',
        textstatus: 'Sửa đơn hàng',
        texttimedate: '16:40 - Quá 2 ngày',
        texterro: '16:40 - Khách hàng không có nhà',
        textname: 'Nguyễn Văn Hùng',
        textaddress: 'Số 10 phố Quần Ngựa, P Liễu Giai, Văn Cao, Hà Nội',
        imagecall: 'ic_main_telephone',
        textcall: 'Gọi điện',
        imagesms: 'ic_main_sms',
        textsms: 'Nhắn tin',
        imagestatus: 'ic_main_noidung',
        textnoidung: 'Thành công',
        imagechuyen: 'ic_main_chuyentt',
        textchuyen: 'Chuyển TT'
    },
    {
        id: '4',
        imagecolor: 'ic_main_ttdonhang_orange',
        textid: '355895476',
        textstore: 'Gia Huy Mobile',
        imageerro: 'ic_main_giao1phan_erro',
        textstatus: '  Giao 1 phần',
        texttimedate: '16:40 - Quá 2 ngày',
        texterro: '16:40 - Khách hàng không có nhà',
        textname: 'Nguyễn Văn A',
        textaddress: 'Số 10 phố Quần Ngựa, P Liễu Giai, Văn Cao, Hà Nội',
        imagecall: 'ic_main_telephone',
        textcall: 'Gọi điện',
        imagesms: 'ic_main_sms',
        textsms: 'Nhắn tin',
        imagestatus: 'ic_main_noidung',
        textnoidung: 'Thành công',
        imagechuyen: 'ic_main_chuyentt',
        textchuyen: 'Chuyển TT'
    },
    {
        id: '5',
        imagecolor: 'ic_main_suadonhang_erro',
        textid: '355895476',
        textstore: 'Gia Huy Mobile',
        imageerro: 'ic_main_suadonhang_erro',
        textstatus: 'Sửa đơn hàng',
        texttimedate: '16:40 - Quá 2 ngày',
        texterro: '16:40 - Khách hàng không có nhà',
        textname: 'Nguyễn Văn A',
        textaddress:
            'Số 10 phố Quần Ngựa, P Liễu Giai, Văn Cao, Ba Đình, Hà Nội',
        imagecall: 'ic_main_telephone',
        textcall: 'Gọi điện',
        imagesms: 'ic_main_sms',
        textsms: 'Nhắn tin',
        imagestatus: 'ic_main_noidung',
        textnoidung: 'Thành công',
        imagechuyen: 'ic_main_chuyentt',
        textchuyen: 'Chuyển TT'
    }
];
export default dataOder;
