const Datainfodonhang = [
    {
        id: '1',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '2',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '3',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    },
    {
        id: '4',
        textstore: 'Chu Thiên Mạnh',
        imagesms: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_sms.png'),
        imagecall: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_telephone.png'),
        imagesoluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_soluong.png'),
        textsoluong: 'Số lượng: 158',
        imagetrongluong: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_trongluong.png'),
        texttrongluong: 'Trọng lượng: 178,300 g',
        imagedatetime: require('./Icon/ic_giaohang_time.png'),
        textdatetime: '18:40 - 22/2/2021',
        imagegiatri: require('../Nhanhang_tbdonnhan/Icon/ic_nhanhang_giatri.png'),
        texttienthuho: 'Tiền thu hộ: ',
        textgiatri: '62,250,000 đ',
        imagenhannhanh: require('../Nhanhang_chonhan/Icon/ic_nhanhang_chonhan_nhannhanh.png'),
        textxacnhan: 'Xác nhận'
    }
];
export default Datainfodonhang;
